# Used in the card_grid.html shortcode to display on the homepage
# the actual [] content doesn't matter much
# add dark_invert = true if you want the image to invert on dark mode
# 
[title1]
url = "/topics/"
src = "/images/peanut_meme.png"
title = "Topics"
text = "See index of conditions"

[title2]
url = "/macros/"
src = "/images/macros.png"
title = "Macros"
text = "Quick, concise, high-yield templates and macros for charting"

[title3]
url = "/tools/spt-generator/"
src = "/images/sptgen.png"
title = "Skin test generator"
text = "Make your skin testing documentation easy!"

[title4]
url = "/medications/"
src = "/images/meds.png"
title = "Medication reference"
text = "High-yield, to-the-point information about common medications"

[title5]
url = "/topics/hypersensitivity/airway_ent/chronic-rhinosinusitis/"
src = "/topic_assets/chronic_rhinosinusitis/normal_sinus.png"
title = "Chronic rhinosinusitis"
text = "An approach to chronic rhinosinusitis with some research deep-dives"

[title6]
url = "/tools/food-protein-index/"
src = "/images/food_protein_index.png"
title = "Food protein index reference"
text = "Searchable database with oral food challenge dose calculations"
